### ISSUE TITLE
Unable to install demo on Windows

### ISSUE THREAD

**Issue by ghost** [jbossdemocentral/rhdm7-install-demo#11]
I'm trying to follow the directions for Option 1 - Install on your machine. The download link under the software section is for jboss-eap-7.2.0.zip, but am getting the following error when running init.ps1:

https://developers.redhat.com/download-manager/file/jboss-eap-7.2.0.zip

**Need to download jboss-eap-7.3.0.zip package from the Customer Support Portal
and place it in the C:\GitHub\DecisionManager\rhdm7-install-demo\installs direct
ory to proceed...**

Is there a different link for downloading jboss-eap-7.3.0.zip? I haven't been able to find this file to download.

**Comment by arundaskd** [comment]
Change the value of **$EAP** to **jboss-eap-7.2.0.zip** in init-properties.ps1 file.

**Comment by DuncanDoyle** [comment]
Fixed with this commit: https://github.com/jbossdemocentral/rhdm7-install-demo/commit/3519ccb432f5c04e2a61d2e1b98f9c69a6844bee#diff-bbdb9b33bb3c01703488f98e13fb2832
