### ISSUE TITLE
There is an issue executing ./init-openshift.sh

### ISSUE THREAD

**Issue by ganuybhat** [jbossdemocentral/rhdm7-install-demo#23]
After entering RHN credentials, in provision.sh script there is an error in the line 273.

########################################################################
Importing Image Streams
########################################################################
imagestream.image.openshift.io/rhdm-decisioncentral-rhel8 created
imagestream.image.openshift.io/rhdm-controller-rhel8 created
imagestream.image.openshift.io/rhdm-kieserver-rhel8 created

Fetching ImageStreams from registry.
./provision.sh: line 273: bc: command not found

########################################################################
Setup completed.
########################################################################

**Comment by udit249** [comment]
I looked into this issue and the solution to this is, you need to install 'bc' package using yum install bc on your linux machine from where you are triggering the script.

**Comment by ganuybhat** [comment]
Thank you udit249.  It worked for me. :)

**Comment by ganuybhat** [comment]
This issue is resolved as per udit249 suggestion.
