### ISSUE TITLE
rhdm7-install-demo on CDK/minishift fails: Missing images

### ISSUE THREAD

**Issue by karstengresch** [jbossdemocentral/rhdm7-install-demo#4]
Followed the instructions for _install-openshift.sh_ on macOS (latest) w/ latest CDK, using oc v3.10.14 (client and server), kubernetes v1.10.0+b81c8f8.

Unfortunately the pods did not come up because of missing images.

Could you please either change the documentation on how to correctly import/tag the images or include the image import into the scripts for minishift, perhaps creating another _install-minishift.sh_ if needed?

Sorry that I cannot provide you w/ more information at the moment, but I need the environment now and am under too high pressure to solve any tag hell problems.

Best wishes,

Karsten

**Comment by DuncanDoyle** [comment]
It should work OOTB now. One of the issues I encountered was the fact that the Images were moved to registry.redhat.io, which is behind a login wall. The new script adjusts the ImageStreams to point to the old registry.access.redhat.com environment.
